include common.mk

MAPNIK_LIBS = $(shell mapnik-config --libs)

libmapnik-jni.dylib: $(SOURCE_DEPENDS)
	$(CXX) -o libmapnik-jni.dylib -dynamiclib \
		$(CFLAGS) \
		$(MAPNIK_CFLAGS) \
		$(JAVA_CFLAGS) \
		mapnikjni.cpp \
		$(LDFLAGS) \
		$(JAVA_LDFLAGS) \
		$(MAPNIK_LIBS)

clean:
	rm libmapnik-jni.dylib
